version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - '5000:80'
      - '5001:443'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    build:
      context: ./server

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  client:
    image: ${DOCKER_REGISTRY-}client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client
# hot reload is not working, it seems to be a windows issue...
#     dockerfile: Dockerfile.dev
