version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - '5000:80'
      - '5001:443'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    build:
      context: .
      dockerfile: WebApp/Dockerfile

  workerservice:
    image: ${DOCKER_REGISTRY-}workerservice
    build:
      context: .
      dockerfile: WorkerService/Dockerfile

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
