version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - '5000:80'
      - '5001:443'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    build:
      context: ./server/WebApi

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    build:
      context: ./client
